### ISSUE TITLE
Component Error Duplicate value 'homepage' detected. All node values must be unique.

### ISSUE THREAD

**Issue by zhouenxian** [Schluca/streamlit_tree_select#11]
First，Thank you for your contributions. when I use the componment , my tree nodes have some same value ,then an error occur:
`Component Error Duplicate value 'homepage' detected. All node values must be unique.`
how to fix it? I would greatly appreciate anyone proposing a solution

**Comment by genatin** [comment]
@zhouenxian @BlueGob  How did you decide that? I have nodes with the same names, but at different levels.

**Comment by genatin** [comment]
i just changed values and its worked for me)
