### ISSUE TITLE
Feature request: Preselected nodes

### ISSUE THREAD

**Issue by Chulean** [Schluca/streamlit_tree_select#5]
Currently, there is only the property 'checked' in which you can insert a list. 
The problem with selecting all items like that is on the user interface the items appear as unchecked -> What I need is a property where I can select which checkboxes should appear as checked + add them to the checked list -> the user sees which of the items are preselected.

**Comment by Chulean** [comment]
made it work.

**Comment by sec-jam** [comment]
@Chulean could you unpack how you made it work? I'm having a very similar problem to your problem description.
